const mongoose = require('mongoose');
const dotenv = require('dotenv');
const OfficialMockExam = require('./src/models/OfficialMockExam');
const User = require('./src/models/User');

dotenv.config();

const seedMocks = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB Connected.');

        let adminUser = await User.findOne({ email: 'admin@engprep.com' });
        if (!adminUser) {
            adminUser = await User.create({
                name: 'EngPrep Admin',
                email: 'admin@engprep.com',
                password: 'password123',
                role: 'ADMIN'
            });
        }

        await OfficialMockExam.deleteMany();
        console.log('Old Official Mocks deleted.');

        const advancedMock = {
            title: 'Cambridge IELTS 18 - Test 1 (CBT Edition)',
            description: 'A fully-featured Computer-Delivered IELTS Simulation based on authentic materials.',
            isActive: true,
            createdBy: adminUser._id,
            listeningAudioUrl: 'https://res.cloudinary.com/dw5fiywyd/video/upload/v1776280302/english-learning/ielts-mock/ielts-mock-listening-lecture.mp3',
            listeningParts: [
                {
                    partNumber: 1,
                    instruction: 'Write ONE WORD ONLY for each answer. Listen to the conversation and fill the gaps.',
                    type: 'gap-fill',
                    questions: [
                        { text: 'Name of customer: John [GAP]', options: [] },
                        { text: 'Address: 42 [GAP] Street', options: [] },
                        { text: 'Telephone: [GAP]', options: [] }
                    ]
                },
                {
                    partNumber: 2,
                    instruction: 'Choose the correct letter, A, B, or C.',
                    type: 'multiple-choice',
                    questions: [
                        { text: 'What is the main topic of the lecture?', options: ['History of Rome', 'Urban Planning', 'Climate Change', ''] },
                        { text: 'When was the castle built?', options: ['12th Century', '13th Century', '15th Century', ''] }
                    ]
                }
            ],
            readingParts: [
                {
                    partNumber: 1,
                    title: 'Urban Heat Islands',
                    text: 'An urban heat island (UHI) is an urban area or metropolitan area that is significantly warmer than its surrounding rural areas due to human activities. The temperature difference is usually larger at night than during the day, and is most apparent when winds are weak. UHI is most noticeable during the summer and winter. The main cause of the urban heat island effect is from the modification of land surfaces.\\n\\nWaste heat generated by energy usage is a secondary contributor. As a population center grows, it tends to expand its area and increase its average temperature. The term heat island is also used; the term can be used to refer to any area that is relatively hotter than the surrounding, but generally refers to human-disturbed areas.',
                    questionGroups: [
                        {
                            instruction: 'Do the following statements agree with the information given? (TRUE/FALSE/NOT GIVEN)',
                            type: 'tfng',
                            questions: [
                                { text: 'UHI is less noticeable during spring.', options: [] },
                                { text: 'Waste heat is the primary cause of UHI.', options: [] }
                            ]
                        },
                        {
                            instruction: 'Complete the sentences below. Choose ONE WORD ONLY.',
                            type: 'gap-fill',
                            questions: [
                                { text: 'The temperature difference is usually larger at [GAP].', options: [] }
                            ]
                        }
                    ]
                },
                {
                    partNumber: 2,
                    title: 'The Evolution of Bicycles',
                    text: 'The bicycle has undergone continuous evolution since its invention. The earliest known ancestor of the bicycle was the "Laufmaschine" (running machine), invented by the German Baron Karl von Drais in 1817. It had two wheels but no pedals; the rider would straddle the wooden frame and push along with their feet.\\n\\nIn the 1860s, the "boneshaker" arrived, featuring pedals attached to the front wheel. It earned its name due to the extremely rough ride caused by its stiff wooden frame and iron-banded wheels. Following this was the penny-farthing, notorious for its massive front wheel which offered higher speeds but terrible safety flaws. The modern era began in the 1880s with the "safety bicycle," which introduced a chain drive linking the pedals to the rear wheel, providing stability and speed.',
                    questionGroups: [
                        {
                            instruction: 'Choose the correct letter, A, B, C or D.',
                            type: 'multiple-choice',
                            questions: [
                                { text: 'Why was the boneshaker given its name?', options: ['It was very fast', 'It had iron-banded wheels', 'It was extremely uncomfortable to ride', 'It was made of bones'] }
                            ]
                        }
                    ]
                }
            ],
            writingTasks: [
                {
                    taskNumber: 1,
                    instruction: 'The chart below shows the number of men and women in further education in Britain in three periods and whether they were studying full-time or part-time.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.',
                    imageUrl: 'https://dummyimage.com/800x400/e0e7ff/3730a3.png&text=[+Bar+Chart+Reference+For+Task+1+]'
                },
                {
                    taskNumber: 2,
                    instruction: 'Some people believe that unpaid community service should be a compulsory part of high school programmes (for example working for a charity, improving the neighborhood or teaching sports to younger children).\n\nTo what extent do you agree or disagree?',
                    imageUrl: ''
                }
            ],
            speakingParts: [
                {
                    partNumber: 1,
                    instruction: 'Let\'s talk about your hometown.',
                    questions: [
                        'Where is your hometown?',
                        'Is it a big city or a small place?',
                        'What do you like most about it?',
                        'Is there anything you dislike about it?'
                    ]
                },
                {
                    partNumber: 2,
                    instruction: 'Describe a memorable journey you have made. You should say:',
                    questions: [
                        'Where you went',
                        'How you travelled',
                        'Why you went on the journey',
                        'And explain why the journey was memorable.'
                    ]
                },
                {
                    partNumber: 3,
                    instruction: 'Discussion Topics - Transport and Travel:',
                    questions: [
                        'How do most people travel long distances in your country?',
                        'Have the types of transport people use changed much over the last few decades?',
                        'What kinds of improvement have there been in transport in your country?'
                    ]
                }
            ]
        };

        await OfficialMockExam.create(advancedMock);
        console.log('Mock Exam CBT populated successfully!');
        process.exit();
    } catch (error) {
        console.error(error);
        process.exit(1);
    }
};

seedMocks();
